import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React, { type ReactElement, type ReactNode } from "react";
import { PrimeReactProvider } from "primereact/api";
import "./global.css";
import "primereact/resources/primereact.min.css";
import "primereact/resources/themes/lara-dark-blue/theme.css";
import "primeicons/primeicons.css";
import "primeflex/primeflex.min.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { generalToastOptions } from "@/config/ReactToastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>): ReactElement {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ToastContainer {...generalToastOptions} />
                <PrimeReactProvider>{children}</PrimeReactProvider>
            </body>
        </html>
    );
}
